### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [jimenda/Colmar#4]
Grade: Need improvement

Summary: Well your html is pretty organized but you have no CSS so it's an incomplete project. I created some issues with tips to improve your html. I'll leave a couple resource links below to supplement the concepts I talk about:
https://www.codecademy.com/articles/accessibility

https://www.pluralsight.com/guides/html-css/semantic-html?aid=701j0000001heIqAAI&promo=&oid=&utm_source=google&utm_medium=ppc&utm_campaign=CA_Dynamic&utm_content=&utm_term=&gclid=CjwKCAjwlrnNBRBMEiwApKU4PBiUM7wtxiyqNw-6Zoikh6ChlNul6tTL839Zj2h_JNTZcK6PE5WWlRoCiOYQAvD_BwE

**Comment by jimenda** [comment]
Thank you for the feedback.

I just realized that I didn't push my changes before I submitted my project.  I apologize.

I finished the project before I moved on to the rest of the lessons in the week so the stuff later on in the week was not included with the project.
